[project]
name = "mazsim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jkolberg", email = "jkolberg@psrc.org" }
]
requires-python = ">=3.10"
dependencies = [
    "autograd>=1.9.0",
    "bokeh>=3.9.1",
    "matplotlib>=3.10.9",
    "numpy>2",
    "orca",
    "pandana",
    "pandera>=0.33.1",
    "pyyaml>=6.0.3",
    "urbansim",
    "urbansim_templates"
]

[project.scripts]
mazsim = "mazsim.cli.main:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

