modelmanager_version: 0.3.dev0

saved_object:
    alt_capacity: vacant_job_spaces
    alt_filters: null
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters: aggr_sector_id == 1
    chooser_sample_size: null
    chooser_size: null
    choosers: jobs
    constrained_choices: true
    fitted_parameters:
    - 0.21591822137050964
    - 1.0913361843106117
    - 0.0981872469243926
    - 0.00010305908076267471
    - 0.4163171686729495
    - -0.5638171675703876
    - 0.5354492303572396
    - -0.0411943935589262
    - -0.6254158693066231
    max_iter: null
    mct_intx_ops: null
    model_expression: major_road_node_sum_800_flat + st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
        + st_prop_aggr_sector_id_5_ave_1600_flat + st_ln_block_groups_mean_home_value
        + st_ln_block_groups_mean_rent + st_ln_block_groups_density_housing_units
        + st_sum_income_ave_1600_flat + st_is_transit_stop_sum_1600_flat + st_total_households_sum_2000_linear
        - 1
    name: jlcm1
    out_alt_filters: vacant_job_spaces > 0
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (aggr_sector_id == 1)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:         133,100\nModel:\
        \         Multinomial Logit   Df Residuals:             133,091\nMethod: \
        \      Maximum Likelihood   Df Model:                       9\nDate:     \
        \            2026-09-11   Pseudo R-squ.:              0.086\nTime:       \
        \               09:52   Pseudo R-bar-squ.:          0.086\nAIC:          \
        \     1,119,968.541   Log-Likelihood:      -559,975.271\nBIC:            \
        \   1,120,056.731   LL-Null:             -612,948.152\n=============================================================================================================================\n\
        \                                                                        \
        \     coef   std err          z     P>|z|   Conf. Int.\n-----------------------------------------------------------------------------------------------------------------------------\n\
        major_road_node_sum_800_flat                                             \
        \  0.2159     0.003     77.203     0.000             \nst_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time\
        \    1.0913     0.006    193.396     0.000             \nst_prop_aggr_sector_id_5_ave_1600_flat\
        \                                     0.0982     0.003     34.164     0.000\
        \             \nst_ln_block_groups_mean_home_value                       \
        \                  0.0001     0.003      0.031     0.975             \nst_ln_block_groups_mean_rent\
        \                                               0.4163     0.004     96.858\
        \     0.000             \nst_ln_block_groups_density_housing_units       \
        \                           -0.5638     0.004   -131.830     0.000       \
        \      \nst_sum_income_ave_1600_flat                                     \
        \           0.5354     0.005    109.461     0.000             \nst_is_transit_stop_sum_1600_flat\
        \                                          -0.0412     0.003    -12.996  \
        \   0.000             \nst_total_households_sum_2000_linear              \
        \                         -0.6254     0.006    -97.325     0.000         \
        \    \n============================================================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.3.dev0
