#----------------------------------------
# settings registered as orca injectables
#----------------------------------------

base_year: 2020
end_year: 2060

calibrated: true

# control total type (regional or subregional)
hh_ct_type: regional
job_ct_type: regional

# use growth rates if no control totals are available
# job_growth_rate: 0.03
# household_growth_rate: 0.03
