modelmanager_version: 0.3.dev0

saved_object:
    alt_capacity: vacant_job_spaces
    alt_filters: null
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters: aggr_sector_id == 2
    chooser_sample_size: null
    chooser_size: null
    choosers: jobs
    constrained_choices: true
    fitted_parameters:
    - 0.052101259587291254
    - 1.7959253496242589
    - -0.13731424585766222
    - 0.11051749657739485
    - 1.0148253162066891
    - -0.6677438187987472
    - 0.2857565651585812
    - 0.13056347040217162
    - -0.7016917027544007
    max_iter: null
    mct_intx_ops: null
    model_expression: major_road_node_sum_800_flat + st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
        + st_prop_aggr_sector_id_5_ave_1600_flat + st_ln_block_groups_mean_home_value
        + st_ln_block_groups_mean_rent + st_ln_block_groups_density_housing_units
        + st_sum_income_ave_1600_flat + st_is_transit_stop_sum_1600_flat + st_total_households_sum_2000_linear
        - 1
    name: jlcm2
    out_alt_filters: vacant_job_spaces > 0
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (aggr_sector_id == 2)
    out_choosers: null
    out_column: null
    summary_table: "                   CHOICEMODELS ESTIMATION RESULTS           \
        \         \n======================================================================\n\
        Dep. Var.:                chosen   No. Observations:           338,563\nModel:\
        \         Multinomial Logit   Df Residuals:               338,554\nMethod:\
        \       Maximum Likelihood   Df Model:                         9\nDate:  \
        \               2026-09-02   Pseudo R-squ.:                0.244\nTime:  \
        \                    15:41   Pseudo R-bar-squ.:            0.244\nAIC:   \
        \            2,357,284.238   Log-Likelihood:      -1,178,633.119\nBIC:   \
        \            2,357,380.830   LL-Null:             -1,559,140.234\n=============================================================================================================================\n\
        \                                                                        \
        \     coef   std err          z     P>|z|   Conf. Int.\n-----------------------------------------------------------------------------------------------------------------------------\n\
        major_road_node_sum_800_flat                                             \
        \  0.0521     0.002     24.287     0.000             \nst_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time\
        \    1.7959     0.005    366.402     0.000             \nst_prop_aggr_sector_id_5_ave_1600_flat\
        \                                    -0.1373     0.002    -68.223     0.000\
        \             \nst_ln_block_groups_mean_home_value                       \
        \                  0.1105     0.002     52.785     0.000             \nst_ln_block_groups_mean_rent\
        \                                               1.0148     0.003    311.996\
        \     0.000             \nst_ln_block_groups_density_housing_units       \
        \                           -0.6677     0.003   -253.950     0.000       \
        \      \nst_sum_income_ave_1600_flat                                     \
        \           0.2858     0.003    104.968     0.000             \nst_is_transit_stop_sum_1600_flat\
        \                                           0.1306     0.002     73.116  \
        \   0.000             \nst_total_households_sum_2000_linear              \
        \                         -0.7017     0.004   -184.667     0.000         \
        \    \n============================================================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.3.dev0
