modelmanager_version: '0.3'

saved_object:
    alt_capacity: vacant_hu_spaces
    alt_filters: null
    alt_sample_size: 50
    alternatives: blocks
    choice_column: maz_id
    chooser_filters: (year_built > 2010) & (unit_type_id == 2)
    chooser_sample_size: null
    chooser_size: null
    choosers: housing_units
    constrained_choices: true
    fitted_parameters:
    - -0.985172330837543
    - 0.099989402599354
    - -1.2473088262114016
    - -0.10522669396423147
    - 0.8145487673667
    - -1.578949526289575
    - 1.5031416686114112
    - 0.0910499809562314
    - -0.06953271613837164
    - -0.7595437025699566
    - 0.5297577196290627
    - 1.0082654952145458
    max_iter: null
    mct_intx_ops: null
    model_expression: st_sum_middle_built_prev_10_years_ave_800_flat + st_sum_income_ave_800_flat
        + st_block_groups_prop_worker_aggr_sector_5 + st_is_urban_center_sum_3200_flat
        + st_sum_middle_ave_3200_flat + st_block_groups_prop_worker_aggr_occ_3 + st_block_groups_prop_worker_aggr_occ_6
        + st_mean_year_built + st_block_groups_median_year_built + st_block_groups_median_income
        + st_ln_res_value_ave_800_flat + st_sum_mf_ave_800_flat - 1
    name: hulcm2_calib
    out_alt_filters: vacant_hu_spaces > 0
    out_alternatives: null
    out_chooser_filters: (maz_id == -1) & (year_built > 2010) & (unit_type_id == 2)
    out_choosers: null
    out_column: null
    summary_table: null
    tags: []
    template: LargeMultinomialLogitStep
    template_version: '0.3'
