modelmanager_version: 0.3.dev0

saved_object:
    alt_capacity: vacant_housing_units
    alt_filters: null
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters: (recent_mover == 1) & (income_quartile == 1)
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 0.4424957873256483
    - -0.3543441730326788
    - -0.1349660510830787
    - 0.021710587624209136
    - -0.03300816170459503
    - -0.3042180194890302
    - 0.08764263845572913
    max_iter: null
    mct_intx_ops: null
    model_expression: st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
        + st_ln_block_groups_mean_rent + st_is_transit_stop_sum_1600_flat + st_sum_income_ave_1600_flat
        + st_block_groups_prop_built_after_2010_1 + st_block_groups_prop_children_0
        + st_ln_block_groups_density_housing_units - 1
    name: hlcm4_calib
    out_alt_filters: vacant_housing_units > 0
    out_alternatives: null
    out_chooser_filters: (block_id == -1) & (income_quartile == 1)
    out_choosers: null
    out_column: null
    summary_table: null
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.3.dev0
