modelmanager_version: 0.3.dev0

saved_object:
    alt_capacity: vacant_hu_spaces
    alt_filters: null
    alt_sample_size: 50
    alternatives: blocks
    choice_column: block_id
    chooser_filters: (year_built > 2010) & (unit_type_id == 1)
    chooser_sample_size: null
    chooser_size: null
    choosers: housing_units
    constrained_choices: true
    fitted_parameters:
    - -0.14099160108110276
    - -0.1432377747000482
    - 0.014582667121584222
    - 0.008980252274819533
    - 0.05136715070062439
    - -0.13127753934904743
    - -0.0010315764136328172
    - 0.7477203579790438
    - -0.1276908677510972
    - -0.2916262532972341
    - 0.02109323805413447
    - -0.13524179969725042
    - -0.31657530561428654
    - 0.5433445129963874
    - 0.348353071092882
    - 2.64646757025557
    max_iter: null
    mct_intx_ops: null
    model_expression: major_road_node_sum_800_flat + st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
        + st_prop_aggr_sector_id_1_ave_1600_flat + st_prop_aggr_sector_id_2_ave_1600_flat
        + st_prop_aggr_sector_id_3_ave_1600_flat + st_prop_aggr_sector_id_4_ave_1600_flat
        + st_prop_aggr_sector_id_5_ave_1600_flat + st_ln_block_groups_mean_home_value
        + st_ln_block_groups_mean_rent + st_total_households_sum_2000_linear + st_block_groups_median_year_built
        + st_is_transit_stop_sum_1600_flat + st_block_groups_median_income + st_block_groups_prop_built_after_2010_1
        + st_prop_children_0_ave_400_flat + st_sum_income_ave_1600_flat - 1
    name: hulcm1
    out_alt_filters: vacant_hu_spaces > 0
    out_alternatives: null
    out_chooser_filters: (block_id == -1) & (year_built > 2010) & (unit_type_id ==
        1)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         20,244\nModel:\
        \         Multinomial Logit   Df Residuals:             20,228\nMethod:  \
        \     Maximum Likelihood   Df Model:                     16\nDate:       \
        \          2026-09-12   Pseudo R-squ.:             0.157\nTime:          \
        \            14:31   Pseudo R-bar-squ.:         0.157\nAIC:              \
        \   133,523.514   Log-Likelihood:      -66,745.757\nBIC:                 133,650.163\
        \   LL-Null:             -79,194.994\n============================================================================================================================\n\
        \                                                                        \
        \     coef   std err         z     P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------------------------------------\n\
        major_road_node_sum_800_flat                                             \
        \ -0.1410     0.013   -11.218     0.000             \nst_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time\
        \   -0.1432     0.012   -12.027     0.000             \nst_prop_aggr_sector_id_1_ave_1600_flat\
        \                                     0.0146     0.006     2.409     0.016\
        \             \nst_prop_aggr_sector_id_2_ave_1600_flat                   \
        \                  0.0090     0.007     1.327     0.184             \nst_prop_aggr_sector_id_3_ave_1600_flat\
        \                                     0.0514     0.007     6.933     0.000\
        \             \nst_prop_aggr_sector_id_4_ave_1600_flat                   \
        \                 -0.1313     0.009   -14.562     0.000             \nst_prop_aggr_sector_id_5_ave_1600_flat\
        \                                    -0.0010     0.007    -0.145     0.885\
        \             \nst_ln_block_groups_mean_home_value                       \
        \                  0.7477     0.033    22.535     0.000             \nst_ln_block_groups_mean_rent\
        \                                              -0.1277     0.011   -11.325\
        \     0.000             \nst_total_households_sum_2000_linear            \
        \                           -0.2916     0.021   -13.897     0.000        \
        \     \nst_block_groups_median_year_built                                \
        \          0.0211     0.013     1.647     0.100             \nst_is_transit_stop_sum_1600_flat\
        \                                          -0.1352     0.011   -12.407   \
        \  0.000             \nst_block_groups_median_income                     \
        \                        -0.3166     0.012   -25.410     0.000           \
        \  \nst_block_groups_prop_built_after_2010_1                             \
        \       0.5433     0.007    75.203     0.000             \nst_prop_children_0_ave_400_flat\
        \                                            0.3484     0.014    24.509  \
        \   0.000             \nst_sum_income_ave_1600_flat                      \
        \                          2.6465     0.033    79.602     0.000          \
        \   \n============================================================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.3.dev0
